services:
    filebrowser:
        image: filebrowser/filebrowser:latest
        container_name: filebrowser
        user: "1000:1000"
        restart: unless-stopped

        volumes:
            - /home/tuckeraa/media:/srv
            - ./database.db:/database.db

        ports:
            - "8085:80"

        networks:
            - MediaServer

networks:
    MediaServer:
        external: true
