global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

log:
  level: DEBUG
  filePath: "/var/log/traefik/traefik.log"
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "internal.valdeze.ch"
            sans:
              - "*.internal.valdeze.ch"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: proxy_net

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: "tucker@valdeze.ch"
      storage: "/letsencrypt/acme.json"
      keyType: EC256
      dnsChallenge:
        provider: cloudflare

serversTransport:
  insecureSkipVerify: true
