secrets:
  infisical_db_pw:
    file: ./secrets/infisical_db_pw.txt

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    image: infisical/infisical:latest # PIN THIS TO A SPECIFIC TAG
    pull_policy: always
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - infisical
      - shared-services
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared-services"
      - "traefik.http.routers.infisical.rule=Host(`infisical.valdeze.ch`)"
      - "traefik.http.routers.infisical.entrypoints=websecure"
      - "traefik.http.routers.infisical.tls.certresolver=cloudflare"
      - "traefik.http.services.infisical.loadbalancer.server.port=8080"

  redis:
    image: redis
    container_name: infisical-redis
    env_file: .env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - infisical
    volumes:
      - redis_data:/data

  db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    env_file: .env
    secrets:
      - infisical_db_pw
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/infisical_db_pw
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB} && psql --username=${POSTGRES_USER} --dbname=${POSTGRES_DB} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  postgresql-backup:
    image: prodrigestivill/postgres-backup-local:14-alpine
    container_name: infisical-postgresql-backup
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    secrets:
      - infisical_db_pw
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/infisical_db_pw
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
    volumes:
      - /docker/Infisical/pgdump:/backups
    networks:
      - infisical

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical:
  shared-services:
    external: true
