// Single control surface for the Fluxer<->Discord voice bridge, reachable
// at one public URL (per Tucker, Sept 17 2026: "a single front facing
// fluxerbridge.valdeze.ch url, simple and clean"). This REPLACES the
// earlier two-panel design (web-panel + user-panel) -- see README.md's
// "Access model, v3" section for why, and the project doc for the full
// history of how this evolved.
//
// ACCESS MODEL (v3):
//   - Log in with Discord OR Fluxer OAuth2. Either creates or resumes an
//     "account" in the local database (db.js), which you can then attach
//     your OTHER platform's identity to as well ("link account").
//   - There is no separate admin login and no Authentik group anymore.
//     Instead, "can you control the bridge on platform X for guild Y" is
//     answered live, every time, by asking that platform itself (via the
//     relevant leg's bot) whether any of your linked identities on X is an
//     admin (Administrator or Manage Server, on Discord; see fluxer-leg's
//     is_guild_admin for the Fluxer equivalent and its caveats) of guild Y
//     right now. Nothing about "being an admin" is stored here or trusted
//     from a token -- it's re-checked on every sensitive action.
//   - If you're not an admin of the guild that's (or should be) bridged,
//     you can generate a hand-off link and send it to someone who is. That
//     link carries NO authority of its own -- it's just a pointer plus
//     some context ("X wants help bridging Y"). Whoever opens it still has
//     to log in and pass the same live admin check as anyone else. See the
//     /claim routes below.
//   - Getting the BOT itself into a new server can't be done from here --
//     see the invite-suggestions section below for why that's a hard
//     platform limit, not something this app is choosing not to automate.
//     What this app DOES do is remove the copy-paste-a-generic-link
//     friction: after logging in, the panel shows you which of YOUR
//     servers (per the guild list your OAuth login already reveals) the
//     bot isn't in yet, with a one-click, pre-filled "add it to THIS
//     server" link, instead of a single static invite URL you'd have to
//     hand out and hope people pick the right server.
//
// This is what actually lets a non-admin who wants the bridge running ask
// a real admin to grant it, per Tucker's original "hand off the request to
// a user on that platform that does [have permission]" ask, without
// building a second privilege system that could itself be abused.

import express from 'express';
import cookieParser from 'cookie-parser';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as db from './db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const {
  DISCORD_LEG_HOST = 'discord-leg',
  DISCORD_LEG_CONTROL_PORT = '5102',
  FLUXER_LEG_HOST = 'fluxer-leg',
  FLUXER_LEG_CONTROL_PORT = '5103',
  PANEL_PORT = '8080',

  PUBLIC_BASE_URL, // e.g. https://fluxerbridge.valdeze.ch -- required
  SESSION_SECRET, // required -- signs the session cookie

  DISCORD_OAUTH_CLIENT_ID,
  DISCORD_OAUTH_CLIENT_SECRET,
  // Must match the Bot Permissions checkboxes actually set on the Discord
  // application's Bot page (View Channels + Connect + Speak, as of Sept
  // 17 2026 -- see README.md). If those checkboxes ever change, update
  // this to match, or invite links generated here will under- or
  // over-request permissions versus what's configured in the portal.
  DISCORD_BOT_INVITE_PERMISSIONS = '3146752',

  FLUXER_INSTANCE_URL = 'https://fluxer.app',
  FLUXER_OAUTH_CLIENT_ID,
  FLUXER_OAUTH_CLIENT_SECRET,
  // Confirmed Sept 17 2026 against a real invite URL generated by Fluxer's
  // own developer portal OAuth2 URL builder: identical bit values to
  // Discord's scheme (View Channels + Connect + Speak = 3146752).
  FLUXER_BOT_INVITE_PERMISSIONS = '3146752',
  // Override for the OAuth2 authorize (consent screen) host. The
  // .well-known/fluxer discovery doc's `endpoints.webapp` claims
  // `web.fluxer.app`, but that host doesn't actually resolve (confirmed
  // Sept 17 2026, DNS_PROBE_POSSIBLE) -- the real, currently-live web
  // client is on the canary channel. Set this explicitly rather than
  // trusting the discovery doc for this one field, and flip it back to
  // unset (falls through to endpoints.webapp) once Fluxer promotes canary
  // to stable and web.fluxer.app actually resolves.
  FLUXER_WEB_BASE_URL = 'https://web.canary.fluxer.app',

  DISCONNECT_COOLDOWN_SECONDS = '30',
  HANDOFF_TOKEN_TTL_HOURS = '24',
} = process.env;

for (const [name, val] of Object.entries({
  PUBLIC_BASE_URL,
  SESSION_SECRET,
  DISCORD_OAUTH_CLIENT_ID,
  DISCORD_OAUTH_CLIENT_SECRET,
  FLUXER_OAUTH_CLIENT_ID,
  FLUXER_OAUTH_CLIENT_SECRET,
})) {
  if (!val) {
    console.error(`FATAL: ${name} is not set -- check .env / Infisical`);
    process.exit(1);
  }
}

const LEGS = {
  discord: `http://${DISCORD_LEG_HOST}:${DISCORD_LEG_CONTROL_PORT}`,
  fluxer: `http://${FLUXER_LEG_HOST}:${FLUXER_LEG_CONTROL_PORT}`,
};

let fluxerApiBase = null;
let fluxerWebBase = null;
async function loadFluxerEndpoints() {
  if (fluxerApiBase && fluxerWebBase) return;
  const res = await fetch(`${FLUXER_INSTANCE_URL}/.well-known/fluxer`);
  if (!res.ok) throw new Error(`well-known lookup failed: ${res.status}`);
  const doc = await res.json();
  fluxerApiBase = `${doc.endpoints.api_public}/v1`;
  // The OAuth2 /authorize (consent screen) page lives on the browser-facing
  // web client, not under api_public -- same split as Discord (discord.com
  // vs discord.com/api). FLUXER_WEB_BASE_URL overrides the discovery doc's
  // own `endpoints.webapp` (see its definition above for why: that field is
  // currently wrong/unresolvable). api_public is still correct for token
  // exchange/userinfo/bot-token API calls -- only the browser-redirect
  // pages needed a different host.
  fluxerWebBase = FLUXER_WEB_BASE_URL || doc.endpoints.webapp;
  if (!fluxerWebBase) throw new Error('no FLUXER_WEB_BASE_URL set and well-known doc has no endpoints.webapp');
}
async function getFluxerApiBase() {
  await loadFluxerEndpoints();
  return fluxerApiBase;
}
async function getFluxerWebBase() {
  await loadFluxerEndpoints();
  return fluxerWebBase;
}

const app = express();
app.use(express.json());
app.use(cookieParser(SESSION_SECRET));

// ---------------------------------------------------------------------
// Session: signed, httpOnly cookie holding only an account id -- no
// platform tokens ever touch this cookie or the database (see db.js).
// ---------------------------------------------------------------------

const SESSION_COOKIE = 'session';
const SESSION_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000; // a week -- linking two
// accounts is enough of a chore that a 1hr session (the old design) would
// be annoying; nothing bearer-capable lives in it, so a longer lifetime
// doesn't raise the stakes much. Reduce this if that trade feels wrong.

function setSession(res, accountId) {
  res.cookie(SESSION_COOKIE, accountId, {
    signed: true,
    httpOnly: true,
    secure: true,
    sameSite: 'lax',
    maxAge: SESSION_MAX_AGE_MS,
  });
}

function getAccountId(req) {
  return req.signedCookies[SESSION_COOKIE] || null;
}

function requireSession(req, res, next) {
  const accountId = getAccountId(req);
  if (!accountId) {
    res.status(401).json({ error: 'not logged in' });
    return;
  }
  req.accountId = accountId;
  next();
}

// ---------------------------------------------------------------------
// OAuth: state/return/mode cookies, shared shape for both providers.
// `returnTo` lets a claim-link visitor land back on /claim/:token after
// logging in; `mode=link` lets an already-logged-in visitor attach a
// second platform identity to their existing account instead of switching
// accounts.
// ---------------------------------------------------------------------

function safeReturnPath(raw) {
  if (typeof raw !== 'string' || !raw.startsWith('/') || raw.startsWith('//')) return '/';
  return raw;
}

function startOAuth(res, { returnTo, link }) {
  const state = crypto.randomBytes(16).toString('hex');
  const cookieOpts = { httpOnly: true, secure: true, sameSite: 'lax', maxAge: 5 * 60 * 1000 };
  res.cookie('oauth_state', state, cookieOpts);
  res.cookie('oauth_return', safeReturnPath(returnTo), cookieOpts);
  res.cookie('oauth_mode', link ? 'link' : 'login', cookieOpts);
  return state;
}

function finishOAuth(req, res) {
  const stateOk = Boolean(req.cookies.oauth_state) && req.cookies.oauth_state === req.query.state;
  const returnTo = safeReturnPath(req.cookies.oauth_return);
  const mode = req.cookies.oauth_mode === 'link' ? 'link' : 'login';
  res.clearCookie('oauth_state');
  res.clearCookie('oauth_return');
  res.clearCookie('oauth_mode');
  return { stateOk, returnTo, mode };
}

// ---------------------------------------------------------------------
// Invite hints: NOT a security boundary, just UX. Discord's (and,
// assuming Fluxer's OAuth mirrors it, Fluxer's) `guilds` scope hands back
// the servers YOU belong to and whether you administer them, straight
// from the OAuth token exchange -- no bot needed. That's exactly the
// "which of my servers could this be added to" list, available before
// the bot has ever joined anything. It's stored in its own short-lived
// signed cookie, separate from the session cookie, and it is NEVER
// consulted for an authorization decision (isAdminOfGuild above always
// asks the leg's bot live) -- it only decides which "add the bridge to
// this server" buttons the UI bothers to show. Worst case if this list
// is stale or wrong: a button links to an invite screen for a server you
// no longer admin, and Discord/Fluxer's own consent screen is what
// actually stops that, not this app.
// ---------------------------------------------------------------------

const INVITE_HINTS_COOKIE = 'invite_hints';
const MAX_HINT_GUILDS = 50; // keep the cookie small regardless of how many servers someone's in

function getInviteHints(req) {
  try {
    return JSON.parse(req.signedCookies[INVITE_HINTS_COOKIE] || '{}');
  } catch {
    return {};
  }
}

function setInviteHints(req, res, provider, guilds) {
  const current = getInviteHints(req);
  current[provider] = guilds.slice(0, MAX_HINT_GUILDS);
  res.cookie(INVITE_HINTS_COOKIE, JSON.stringify(current), {
    signed: true,
    httpOnly: true,
    secure: true,
    sameSite: 'lax',
    maxAge: SESSION_MAX_AGE_MS,
  });
}

// Discord: well-documented. GET /users/@me/guilds with the user's own
// Bearer token (not the bot's) returns every guild they're in, each with
// an `owner` flag and a `permissions` bitfield -- no bot presence
// required. ADMINISTRATOR = 0x8, MANAGE_GUILD = 0x20.
async function fetchDiscordOwnedGuilds(accessToken) {
  const res = await fetch('https://discord.com/api/users/@me/guilds', {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`guilds fetch failed: ${res.status}`);
  const guilds = await res.json();
  return guilds
    .filter((g) => g.owner || (BigInt(g.permissions ?? '0') & (0x8n | 0x20n)) !== 0n)
    .map((g) => ({ id: g.id, name: g.name }));
}

// Fluxer: UNCONFIRMED. Assumes the same `GET /users/@me/guilds` shape
// works with a Bearer user token (fluxer-leg's bot-token call to the same
// path is confirmed; the Bearer-token variant for a logged-in user is
// not). Fails soft to an empty list -- worst case, no invite-suggestion
// buttons show up for Fluxer until this is verified, which is a strictly
// safer failure than guessing wrong.
async function fetchFluxerOwnedGuilds(apiBase, accessToken) {
  try {
    const res = await fetch(`${apiBase}/users/@me/guilds`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!res.ok) return [];
    const guilds = await res.json();
    return guilds
      .filter((g) => g.owner || (BigInt(g.permissions ?? '0') & (0x8n | 0x20n)) !== 0n)
      .map((g) => ({ id: g.id, name: g.name }));
  } catch (err) {
    console.warn('fetchFluxerOwnedGuilds failed (non-fatal, unconfirmed endpoint):', err.message);
    return [];
  }
}

async function buildInviteUrl(provider, guildId) {
  if (provider === 'discord') {
    const url = new URL('https://discord.com/oauth2/authorize');
    url.searchParams.set('client_id', DISCORD_OAUTH_CLIENT_ID);
    url.searchParams.set('scope', 'bot');
    url.searchParams.set('integration_type', '0');
    if (DISCORD_BOT_INVITE_PERMISSIONS) url.searchParams.set('permissions', DISCORD_BOT_INVITE_PERMISSIONS);
    url.searchParams.set('guild_id', guildId);
    url.searchParams.set('disable_guild_select', 'true');
    return url.toString();
  }
  // Fluxer: confirmed Sept 17 2026 against a real generated invite URL from
  // the Fluxer developer portal's own OAuth2 URL builder -- the authorize
  // page lives on the web client host (endpoints.webapp), not api_public,
  // and `permissions` uses the exact same bit values as Discord's scheme
  // (View Channels + Connect + Speak = 3146752 confirmed identical).
  const webBase = await getFluxerWebBase();
  const url = new URL(`${webBase}/oauth2/authorize`);
  url.searchParams.set('client_id', FLUXER_OAUTH_CLIENT_ID);
  url.searchParams.set('scope', 'bot');
  if (FLUXER_BOT_INVITE_PERMISSIONS) url.searchParams.set('permissions', FLUXER_BOT_INVITE_PERMISSIONS);
  url.searchParams.set('guild_id', guildId);
  return url.toString();
}

async function completeLogin(req, res, { provider, platformUserId, username, returnTo, mode, ownedGuilds }) {
  if (Array.isArray(ownedGuilds)) setInviteHints(req, res, provider, ownedGuilds);

  if (mode === 'link') {
    const existingAccount = getAccountId(req);
    if (!existingAccount) {
      res.status(400).send('link requested but you are not logged in -- log in first, then link your other account from the panel.');
      return;
    }
    const ownerOfIdentity = db.findAccountIdByIdentity(provider, platformUserId);
    if (ownerOfIdentity && ownerOfIdentity !== existingAccount) {
      // That identity is already someone else's account. Rather than
      // silently merging two accounts, switch the session to the
      // identity's existing account -- the least surprising behavior
      // available without a real account-merge UI (not built here).
      console.warn(`link: ${provider}:${platformUserId} already belongs to a different account -- switching session to it instead of merging`);
      setSession(res, ownerOfIdentity);
    } else {
      db.linkIdentity(existingAccount, provider, platformUserId, username);
    }
  } else {
    const accountId = db.getOrCreateAccountForIdentity(provider, platformUserId, username);
    setSession(res, accountId);
  }
  res.redirect(returnTo);
}

// ---------------------------------------------------------------------
// Discord OAuth2.
// ---------------------------------------------------------------------

const DISCORD_AUTHORIZE_URL = 'https://discord.com/oauth2/authorize';
const DISCORD_TOKEN_URL = 'https://discord.com/api/oauth2/token';
const DISCORD_USER_URL = 'https://discord.com/api/users/@me';
const DISCORD_REDIRECT_URI = `${PUBLIC_BASE_URL}/auth/discord/callback`;

app.get('/auth/discord/login', (req, res) => {
  const link = req.query.link === '1' && Boolean(getAccountId(req));
  const state = startOAuth(res, { returnTo: req.query.returnTo, link });
  const url = new URL(DISCORD_AUTHORIZE_URL);
  url.searchParams.set('client_id', DISCORD_OAUTH_CLIENT_ID);
  url.searchParams.set('redirect_uri', DISCORD_REDIRECT_URI);
  url.searchParams.set('response_type', 'code');
  url.searchParams.set('scope', 'identify guilds');
  url.searchParams.set('state', state);
  res.redirect(url.toString());
});

app.get('/auth/discord/callback', async (req, res) => {
  const { stateOk, returnTo, mode } = finishOAuth(req, res);
  if (!stateOk) {
    res.status(400).send('invalid or expired OAuth state -- try logging in again');
    return;
  }
  try {
    const tokenRes = await fetch(DISCORD_TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: DISCORD_OAUTH_CLIENT_ID,
        client_secret: DISCORD_OAUTH_CLIENT_SECRET,
        grant_type: 'authorization_code',
        code: req.query.code,
        redirect_uri: DISCORD_REDIRECT_URI,
      }),
    });
    if (!tokenRes.ok) throw new Error(`token exchange failed: ${tokenRes.status}`);
    const { access_token } = await tokenRes.json();

    const userRes = await fetch(DISCORD_USER_URL, { headers: { Authorization: `Bearer ${access_token}` } });
    if (!userRes.ok) throw new Error(`user fetch failed: ${userRes.status}`);
    const user = await userRes.json();

    let ownedGuilds = [];
    try {
      ownedGuilds = await fetchDiscordOwnedGuilds(access_token);
    } catch (err) {
      console.warn('fetchDiscordOwnedGuilds failed (non-fatal -- invite suggestions will be empty):', err.message);
    }
    // access_token is discarded here -- never persisted (see db.js).

    await completeLogin(req, res, { provider: 'discord', platformUserId: user.id, username: user.username, returnTo, mode, ownedGuilds });
  } catch (err) {
    console.error('Discord OAuth error:', err);
    res.status(500).send('Discord login failed -- see server logs');
  }
});

// ---------------------------------------------------------------------
// Fluxer OAuth2.
// ---------------------------------------------------------------------

const FLUXER_REDIRECT_URI = `${PUBLIC_BASE_URL}/auth/fluxer/callback`;

app.get('/auth/fluxer/login', async (req, res) => {
  try {
    const webBase = await getFluxerWebBase();
    const link = req.query.link === '1' && Boolean(getAccountId(req));
    const state = startOAuth(res, { returnTo: req.query.returnTo, link });
    const url = new URL(`${webBase}/oauth2/authorize`);
    url.searchParams.set('client_id', FLUXER_OAUTH_CLIENT_ID);
    url.searchParams.set('redirect_uri', FLUXER_REDIRECT_URI);
    url.searchParams.set('response_type', 'code');
    url.searchParams.set('scope', 'identify guilds');
    url.searchParams.set('state', state);
    res.redirect(url.toString());
  } catch (err) {
    console.error('Fluxer OAuth init error:', err);
    res.status(502).send('could not reach the Fluxer instance -- see server logs');
  }
});

app.get('/auth/fluxer/callback', async (req, res) => {
  const { stateOk, returnTo, mode } = finishOAuth(req, res);
  if (!stateOk) {
    res.status(400).send('invalid or expired OAuth state -- try logging in again');
    return;
  }
  try {
    const apiBase = await getFluxerApiBase();
    const tokenRes = await fetch(`${apiBase}/oauth2/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: FLUXER_OAUTH_CLIENT_ID,
        client_secret: FLUXER_OAUTH_CLIENT_SECRET,
        grant_type: 'authorization_code',
        code: req.query.code,
        redirect_uri: FLUXER_REDIRECT_URI,
      }),
    });
    if (!tokenRes.ok) throw new Error(`token exchange failed: ${tokenRes.status}`);
    const { access_token } = await tokenRes.json();

    const userRes = await fetch(`${apiBase}/oauth2/userinfo`, { headers: { Authorization: `Bearer ${access_token}` } });
    if (!userRes.ok) throw new Error(`userinfo fetch failed: ${userRes.status}`);
    const user = await userRes.json();

    const ownedGuilds = await fetchFluxerOwnedGuilds(apiBase, access_token); // fails soft to [] -- see its comment

    await completeLogin(req, res, { provider: 'fluxer', platformUserId: user.id, username: user.username, returnTo, mode, ownedGuilds });
  } catch (err) {
    console.error('Fluxer OAuth error:', err);
    res.status(500).send('Fluxer login failed -- see server logs');
  }
});

app.get('/logout', (req, res) => {
  res.clearCookie(SESSION_COOKIE);
  res.redirect('/');
});

// ---------------------------------------------------------------------
// Live permission checks -- ask the relevant leg's bot, every time. This
// is the actual security boundary for everything below; nothing stored in
// db.js is trusted as proof of admin status on its own.
// ---------------------------------------------------------------------

async function legJson(base, urlPath, init) {
  const res = await fetch(`${base}${urlPath}`, init);
  if (!res.ok) throw new Error(`${urlPath} -> ${res.status}`);
  return res.json();
}

async function isAdminOfGuild(provider, guildId, accountId) {
  const identities = db.getIdentitiesForProvider(accountId, provider);
  if (identities.length === 0) return false;
  const base = LEGS[provider];
  for (const identity of identities) {
    try {
      const { isAdmin } = await legJson(base, `/guilds/${guildId}/members/${identity.platformUserId}/is-admin`);
      if (isAdmin) return true;
    } catch (err) {
      console.warn(`is-admin check failed (${provider} ${guildId} ${identity.platformUserId}):`, err.message);
    }
  }
  return false;
}

async function adminGuildsFor(provider, accountId) {
  const identities = db.getIdentitiesForProvider(accountId, provider);
  if (identities.length === 0) return [];
  const base = LEGS[provider];
  const byId = new Map();
  for (const identity of identities) {
    try {
      const guilds = await legJson(base, `/users/${identity.platformUserId}/admin-guilds`);
      for (const g of guilds) byId.set(g.id, g);
    } catch (err) {
      console.warn(`admin-guilds lookup failed (${provider} ${identity.platformUserId}):`, err.message);
    }
  }
  return [...byId.values()];
}

// ---------------------------------------------------------------------
// API consumed by the page.
// ---------------------------------------------------------------------

app.get('/api/me', (req, res) => {
  const accountId = getAccountId(req);
  if (!accountId) {
    res.json({ loggedIn: false });
    return;
  }
  res.json({ loggedIn: true, accountId, identities: db.getIdentities(accountId) });
});

app.get('/api/my-guilds', requireSession, async (req, res) => {
  const provider = req.query.provider;
  if (!LEGS[provider]) {
    res.status(400).json({ error: 'provider must be discord or fluxer' });
    return;
  }
  try {
    res.json(await adminGuildsFor(provider, req.accountId));
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

// Servers you (per your own OAuth guild list -- see the Invite hints
// comment above) administer where the bot ISN'T a member yet, each with a
// ready-to-click invite link. Purely a convenience list -- adding the bot
// still requires the admin themselves to click through that link and hit
// Discord's/Fluxer's own Authorize screen; nothing here bypasses that.
app.get('/api/invite-suggestions', requireSession, async (req, res) => {
  const provider = req.query.provider;
  if (!LEGS[provider]) {
    res.status(400).json({ error: 'provider must be discord or fluxer' });
    return;
  }
  try {
    const hinted = getInviteHints(req)[provider] || [];
    if (hinted.length === 0) {
      res.json([]);
      return;
    }
    const alreadyJoined = new Set((await legJson(LEGS[provider], '/guilds')).map((g) => g.id));
    const missing = hinted.filter((g) => !alreadyJoined.has(g.id));
    const withLinks = await Promise.all(
      missing.map(async (g) => ({ ...g, inviteUrl: await buildInviteUrl(provider, g.id) }))
    );
    res.json(withLinks.filter((g) => g.inviteUrl));
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.get('/api/guilds/:provider/:guildId/channels', requireSession, async (req, res) => {
  const { provider, guildId } = req.params;
  if (!LEGS[provider]) {
    res.status(400).json({ error: 'provider must be discord or fluxer' });
    return;
  }
  // Only expose channels for guilds this account actually administers --
  // channel names aren't hugely sensitive, but there's no reason to leak
  // them to every logged-in visitor either.
  if (!(await isAdminOfGuild(provider, guildId, req.accountId))) {
    res.status(403).json({ error: 'you are not an admin of that guild' });
    return;
  }
  try {
    res.json(await legJson(LEGS[provider], `/guilds/${guildId}/channels`));
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.get('/api/status', async (req, res) => {
  const accountId = getAccountId(req);
  const result = {};
  for (const provider of ['discord', 'fluxer']) {
    try {
      const status = await legJson(LEGS[provider], '/status');
      let canControl = false;
      if (accountId && status.connected && status.current) {
        canControl = await isAdminOfGuild(provider, status.current.guildId ?? status.current.guild_id, accountId);
      }
      result[provider] = { connected: status.connected, current: status.current, canControl };
    } catch (err) {
      result[provider] = { error: `could not reach the ${provider} leg: ${err.message}` };
    }
  }
  res.json({ loggedIn: Boolean(accountId), legs: result });
});

app.post('/api/connect', requireSession, async (req, res) => {
  const { provider, guildId, channelId, guildName, channelName } = req.body || {};
  if (!LEGS[provider] || !guildId || !channelId) {
    res.status(400).json({ error: 'provider, guildId and channelId are required' });
    return;
  }
  if (!(await isAdminOfGuild(provider, guildId, req.accountId))) {
    res.status(403).json({ error: 'you are not an admin of that guild' });
    return;
  }
  try {
    const body = provider === 'fluxer' ? { guildId, channelId, guildName, channelName } : { guildId, channelId };
    const upstream = await fetch(`${LEGS[provider]}/connect`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    const payload = await upstream.json();
    res.status(upstream.status).json(payload);
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

const lastDisconnectAt = new Map(); // `${accountId}:${provider}` -> ms epoch

app.post('/api/disconnect', requireSession, async (req, res) => {
  const { provider } = req.body || {};
  if (!LEGS[provider]) {
    res.status(400).json({ error: 'provider must be discord or fluxer' });
    return;
  }

  const key = `${req.accountId}:${provider}`;
  const cooldownMs = Number(DISCONNECT_COOLDOWN_SECONDS) * 1000;
  const last = lastDisconnectAt.get(key);
  if (last && Date.now() - last < cooldownMs) {
    res.status(429).json({ error: `wait ${Math.ceil((cooldownMs - (Date.now() - last)) / 1000)}s before trying again` });
    return;
  }

  try {
    const status = await legJson(LEGS[provider], '/status');
    if (!status.connected || !status.current) {
      res.status(409).json({ error: 'not currently bridged on that side' });
      return;
    }
    const guildId = status.current.guildId ?? status.current.guild_id;
    // Always re-check live, right before acting -- never trust an earlier
    // pass of this same check.
    if (!(await isAdminOfGuild(provider, guildId, req.accountId))) {
      res.status(403).json({ error: 'you are not an admin of the currently bridged guild' });
      return;
    }
    await fetch(`${LEGS[provider]}/disconnect`, { method: 'POST' });
    lastDisconnectAt.set(key, Date.now());
    res.json({ ok: true });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

// ---------------------------------------------------------------------
// Hand-off links. Deliberately NOT a capability grant -- see the comment
// at the top of this file. Creating one just needs a session; claiming one
// still runs the exact same live admin check as every other action here.
// ---------------------------------------------------------------------

app.post('/api/handoff/request', requireSession, async (req, res) => {
  const { provider } = req.body || {};
  if (!LEGS[provider]) {
    res.status(400).json({ error: 'provider must be discord or fluxer' });
    return;
  }
  try {
    const status = await legJson(LEGS[provider], '/status');
    if (!status.connected || !status.current) {
      res.status(409).json({ error: 'nothing is bridged on that side right now to request access to' });
      return;
    }
    const guildId = status.current.guildId ?? status.current.guild_id;
    const guildName = status.current.guildName ?? status.current.guild_name;
    const token = db.createHandoffToken({
      provider,
      guildId,
      guildName,
      requestedByAccountId: req.accountId,
      ttlMs: Number(HANDOFF_TOKEN_TTL_HOURS) * 60 * 60 * 1000,
    });
    res.json({ url: `${PUBLIC_BASE_URL}/claim/${token}` });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.get('/api/claim/:token', (req, res) => {
  const row = db.getHandoffToken(req.params.token);
  if (!row) {
    res.status(404).json({ error: 'unknown or expired link' });
    return;
  }
  res.json({
    provider: row.provider,
    guildId: row.guildId,
    guildName: row.guildName,
    expired: Date.now() > row.expiresAt,
    claimed: Boolean(row.claimedByAccountId),
    claimedByUsername: row.claimedByAccountId ? db.usernameForAccount(row.claimedByAccountId, row.provider) : null,
    requestedByUsername: db.usernameForAccount(row.requestedByAccountId, row.provider),
  });
});

app.post('/api/claim/:token', requireSession, async (req, res) => {
  const row = db.getHandoffToken(req.params.token);
  if (!row) {
    res.status(404).json({ error: 'unknown or expired link' });
    return;
  }
  if (Date.now() > row.expiresAt) {
    res.status(410).json({ error: 'this link has expired -- ask for a new one' });
    return;
  }
  const isAdmin = await isAdminOfGuild(row.provider, row.guildId, req.accountId);
  if (!isAdmin) {
    res.status(403).json({
      error: `your ${row.provider} account isn't an admin of ${row.guildName || 'that server'}. If that's wrong, make sure you've linked the right ${row.provider} account.`,
    });
    return;
  }
  db.markHandoffClaimed(req.params.token, req.accountId);
  res.json({ ok: true });
});

app.get('/claim/:token', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.use(express.static(path.join(__dirname, 'public')));

app.listen(Number(PANEL_PORT), () => {
  console.log(`panel listening on :${PANEL_PORT}`);
});
